//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospedagemOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoria
    {
        public Categoria()
        {
            this.Estabelecimento = new HashSet<Estabelecimento>();
        }
    
        public int IdCategoria { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Estabelecimento> Estabelecimento { get; set; }
    }
}
