//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospedagemOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estabelecimento
    {
        public Estabelecimento()
        {
            this.Quarto = new HashSet<Quarto>();
        }
    
        public int IdEstab { get; set; }
        public int IdCidade { get; set; }
        public int IdCategoria { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Telefone { get; set; }
        public string Site { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Cidade Cidade { get; set; }
        public virtual ICollection<Quarto> Quarto { get; set; }
    }
}
