//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospedagemOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoQuarto
    {
        public TipoQuarto()
        {
            this.Quarto = new HashSet<Quarto>();
        }
    
        public int IdTipoQuarto { get; set; }
        public string Descricao { get; set; }
        public double ValorDiraria { get; set; }
        public bool CafeManha { get; set; }
    
        public virtual ICollection<Quarto> Quarto { get; set; }
    }
}
